name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ "3.10" ]

    steps:
    - name: Get repository
      uses: actions/checkout@v3

    - name: Set up virtual X11
      run: sudo apt-get install xvfb

    - name: Set up PyQt dependencies
      uses: tlambert03/setup-qt-libs@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Update pip and install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Freeze requirements
      run: pipenv requirements --dev > requirements.txt

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install pytest-xvfb
      run: pip install pytest-xvfb

    # - name: Lint with flake8
    # run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: xvfb-run -a pytest
